env:
   - TERM=dumb

sudo: false

language: groovy
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

cache:
  directories:
  - "$HOME/.gradle/caches/"

before_install:
 - chmod +x gradlew

after_success:
 - ./gradlew jacocoTestReport coveralls

after_failure:
 - ./gradlew clean check --debug
